# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f772f05caa65fd2718062ee1f77d040ebd6a281bc86858e350168b485a26e74ca71ce5890004c7a8c099360b764472e476d5bb3c9401794e416e83318fcf34

test:
  secret_key_base: 48d951e1e796b9e154c57aaccbba7f3b42353d1aeb74ed1870a94883f4cc2c96f80d6e165507d91bb7252eea513fce6a89ee4492d4af2e3835a99cf46f0974dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
